### ISSUE TITLE
Felix can attempt to create a route before the interface is up

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#104]
I'm running a new CI script: test_add_group_rule() and it creates a bunch of VMs at the beginning.  Felix logs show it hitting an unhandled exception when I run it:

2015-01-14 16:24:48,865 [INFO] calico.felix.endpoint 156: Add route to IPv4 address 10.65.0.87 for tap tapdc47bb82-5d
2015-01-14 16:24:48,886 [ERROR] calico.felix.felix 728: Felix exiting after uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 725, in main
    agent.run()
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 695, in run
    if endpoint.program_endpoint():
  File "/usr/lib/python2.7/dist-packages/calico/felix/endpoint.py", line 157, in program_endpoint
    finterface.add_route(futils.IPV4, ipv4, self.tap, self.mac)
  File "/usr/lib/python2.7/dist-packages/calico/felix/finterface.py", line 98, in add_route
    futils.check_call(["ip", "route", "add", ip, "dev", tap])
  File "/usr/lib/python2.7/dist-packages/calico/felix/futils.py", line 93, in check_call
    raise FailedSystemCall("Failed system call", args, retcode, stdout, stderr)
FailedSystemCall: Failed system call (retcode : 2, args : ('ip', 'route', 'add', '10.65.0.87', 'dev', 'tapdc47bb82-5d'))
  stdout  :
  stderr  : RTNETLINK answers: Network is down

2015-01-14 16:24:49,517 [ERROR] calico.felix.felix 70: Felix starting

Looks like Felix is trying to program the route before the tap interface is ready.

**Comment by lwr20** [comment]
Diags added to diags server (calico-jenkins).

**Comment by plwhite** [comment]
Felix has checked that the tap interface exists, but it is quite possible that this error is an artefact of the interface existing but not being complete. It should be fairly easy to fix.

As a note to myself, that would require catching the error, logging it, and adding it to "ep_retry". Sadly, I suspect that requires adding some error information to the right function interfaces, which is tedious (a couple of hours to do).

**Comment by Lukasa** [comment]
Fixed in #117.
