### ISSUE TITLE
Felix cyclically restarts when previous state is in iptables6

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico#237]
I'm seeing an issue where old iptables6 state appears to be causing felix to cyclically restart.  In the traceback below `tape25102c4c2c` is not an active endpoint from the EP API.  It must be finding out about the (now nonexistent) interface via state leftover in iptables6 or ipsets from before a hard restart of felix.  

```
2015-03-04 22:57:46,451 [ERROR] calico.felix.felix 807: Felix exiting after uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 798, in main
    agent.run()
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 725, in run
    self.complete_endpoint_resync(False)
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 263, in complete_endpoint_resync
    frules.del_rules(self.iptables_state, found_suffix, type)
  File "/usr/lib/python2.7/dist-packages/calico/felix/frules.py", line 496, in del_rules
    iptables_state.apply()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fiptables.py", line 440, in apply
    futils.multi_call(ops)
  File "/usr/lib/python2.7/dist-packages/calico/felix/futils.py", line 112, in multi_call
    check_call(["bash", name])
  File "/usr/lib/python2.7/dist-packages/calico/felix/futils.py", line 90, in check_call
    raise FailedSystemCall("Failed system call", args, retcode, stdout, stderr)
FailedSystemCall: Failed system call (retcode : 1, args : ('bash', '/tmp/tmp3PgfsM'))
  stdout  : Executing : ip6tables --wait --table filter --delete felix-TO-ENDPOINT -o tape25102c4c2c -j felix-to-e25102c4c2c

  stderr  : ip6tables: No chain/target/match by that name.

```

**Comment by spikecurtis** [comment]
Full logs from one felix cycle are at http://pastebin.com/pdaSkwnF

**Comment by Lukasa** [comment]
Felix seems to get all in a tizzy here.

It's going to remove state for a VM that it no longer owns, which includes some stuff in iptables. When it decides to remove it, it emits the following logs:

```
2015-03-04 22:57:46,975 [WARNING] calico.felix.felix 262: Removing IPv6 rules for removed object e25102c4c2c
2015-03-04 22:57:46,975 [DEBUG] calico.felix.frules 458: Delete IPv6 rules for e25102c4c2c
2015-03-04 22:57:46,975 [DEBUG] calico.felix.fiptables 69: Removing rule : ['ip6tables', '--wait', '--table', 'filter', '--delete', 'felix-TO-ENDPOINT', '-o', 'tape25102c4c2c', '-j', 'felix-to-e25102c4c2c']
2015-03-04 22:57:46,975 [DEBUG] calico.felix.fiptables 69: Removing rule : ['ip6tables', '--wait', '--table', 'filter', '--delete', 'felix-FROM-ENDPOINT', '-i', 'tape25102c4c2c', '-j', 'felix-from-e25102c4c2c']
2015-03-04 22:57:46,975 [DEBUG] calico.felix.frules 489: Flush chain felix-from-e25102c4c2c
2015-03-04 22:57:46,975 [DEBUG] calico.felix.fiptables 51: Flushing chain felix-from-e25102c4c2c
2015-03-04 22:57:46,976 [DEBUG] calico.felix.frules 491: Delete chain felix-from-e25102c4c2c
2015-03-04 22:57:46,976 [DEBUG] calico.felix.fiptables 222: Delete chain felix-from-e25102c4c2c from table filter (IPv6)
2015-03-04 22:57:46,976 [DEBUG] calico.felix.frules 489: Flush chain felix-to-e25102c4c2c
2015-03-04 22:57:46,976 [DEBUG] calico.felix.fiptables 51: Flushing chain felix-to-e25102c4c2c
2015-03-04 22:57:46,976 [DEBUG] calico.felix.frules 491: Delete chain felix-to-e25102c4c2c
2015-03-04 22:57:46,976 [DEBUG] calico.felix.fiptables 222: Delete chain felix-to-e25102c4c2c from table filter (IPv6)
2015-03-04 22:57:46,976 [DEBUG] calico.felix.fiptables 439: Apply batched changes to tables
2015-03-04 22:57:46,977 [DEBUG] calico.felix.futils 99: Calling out to system : [['ip6tables', '--wait', '--table', 'filter', '--delete', 'felix-TO-ENDPOINT', '-o', 'tape25102c4c2c', '-j', 'felix-to-e25102c4c2c'], ['ip6tables', '--wait', '--table', 'filter', '--delete', 'felix-FROM-ENDPOINT', '-i', 'tape25102c4c2c', '-j', 'felix-from-e25102c4c2c'], ['ip6tables', '--wait', '--table', 'filter', '--flush', 'felix-from-e25102c4c2c'], ['ip6tables', '--wait', '--table', 'filter', '--delete-chain', 'felix-from-e25102c4c2c'], ['ip6tables', '--wait', '--table', 'filter', '--flush', 'felix-to-e25102c4c2c'], ['ip6tables', '--wait', '--table', 'filter', '--delete-chain', 'felix-to-e25102c4c2c']]
2015-03-04 22:57:46,977 [DEBUG] calico.felix.futils 82: Calling out to system : ['bash', '/tmp/tmptwwf0X']
```

**Comment by Lukasa** [comment]
Relevantly, Felix wants to make these changes:

```
ip6tables --wait --table filter --delete felix-TO-ENDPOINT -o tape25102c4c2c -j
felix-to-e25102c4c2c
ip6tables --wait --table filter --delete felix-FROM-ENDPOINT -i tape25102c4c2c -
j felix-from-e25102c4c2c
ip6tables --wait --table filter --flush felix-from-e25102c4c2c
ip6tables --wait --table filter --delete-chain felix-from-e25102c4c2c
ip6tables --wait --table filter --flush felix-to-e25102c4c2c
ip6tables --wait --table filter --delete-chain felix-to-e25102c4c2c
```

**Comment by Lukasa** [comment]
We fail extremely early, on the first command. That's a bit stupid, because earlier on when Felix started it printed:

```
2015-03-04 22:57:46,604 [DEBUG] calico.felix.fiptables 469: Found rule in table filter : -A felix-TO-ENDPOINT -o tape25102c4c2c -j felix-to-e25102c4c2c
```

**Comment by Lukasa** [comment]
It might be interesting to see if that command actually does fail even when a rule that apparently matches it is in ip6tables.

**Comment by plwhite** [comment]
The code appears right on a first look. The logic is as follows.

* Felix starts up and scans the rules. It finds a rule for this interface.
* It detects that this interface should not exist any more.
* It then tries to remove the rule that it found (and it gets that rule by reading it with a call to ip6tables).

I at first thought that it was removing a rule that it found using IP v4 tables but with IP v6 (since that would be a very plausible sort of bug), but the code looks right here.

**Comment by plwhite** [comment]
Next steps are probably to manually look at the ip6tables state to ensure that the state really exists, and to manually try running the exact same command on the server.

**Comment by spikecurtis** [comment]
I'll let y'all know if I see this again.  I rebooted my box to clear the bogus state so I could continue working.

**Comment by spikecurtis** [comment]
I'm seeing this again, this time on CoreOS.  Diagnostics are at:

https://dl.dropboxusercontent.com/u/4550074/diags-20150313_182042.tar.gz

**Comment by spikecurtis** [comment]
I've done some more digging on my live system.

It appears that commands like 

`ip6tables --wait --table filter --delete felix-TO-ENDPOINT -o tape25102c4c2c -j
felix-to-e25102c4c2c`

will fail if the referenced interface does not exist, even if the rule persists.  I checked the state of `ip6tables` on the live system and confirmed that the rule exists.  Deleting this way does work for interfaces that do exist.

I was able to delete the rule by number, e.g.

`ip6tables --wait --table filter --delete felix-TO-ENDPOINT 2`

It appears this is a bug in `ip6tables`.  We could work around it by deleting by number.  You can get the numbers by using the `--line-numbers` option, e.g.

`iptables -L felix-TO-ENDPOINT --line-numbers`

**Comment by plwhite** [comment]
Very odd - we've seen that you cannot explicitly specify an interface which does not exist, but can no longer repro. There's clearly something inconsistent in what we are doing now with what we used to be doing (maybe even IPv4 vs. IPv6).

We'll dig into this in the new Felix code.

**Comment by plwhite** [comment]
I had a dig into this - it is not IPv4 vs. v6. I cannot repro on an ubuntu box running 1.4.21, which is the same version as these logs come from. Various internet searches imply that specifying an arbitrary interface name is legal and common, and seems to have been for a long time.

I half wondered if this was a problem with the CoreOS kernel version, but that seems very unlikely. More plausible is that you cannot delete the rule because the kernel module you need to manipulate the rule has not been correctly loaded, but even that seems a bit of a stretch.

I'm going to keep this issue open, but I don't think we can do anything to fix it without understanding better what environment shows the problem. @spikecurtis, can you tell us which exact OS and kernel version this was on?

**Comment by fasaxc** [comment]
@plwhite  Can we close this now, I don't think we've seen anything like it for a long time and it's pre-etcd by the looks of it?

**Comment by plwhite** [comment]
If we don't have a repro, we should just close it, agreed.
