### ISSUE TITLE
Felix dies if /calico key is missing from etcd.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#309]
Felix should presumably be somewhat resilient to etcd existing but being uninitialized. As it stands, right now Felix will launch and crash repeatedly, eventually causing the init system to leave it dead. That's less than idea.

Felix should be able to tolerate the absence of this key until such time as it appears.

The traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/calico-0.14-py2.7.egg/calico/felix/felix.py", line 156, in main
    config = Config("/etc/calico/felix.cfg")
  File "/usr/local/lib/python2.7/dist-packages/calico-0.14-py2.7.egg/calico/felix/config.py", line 79, in __init__
    self.ETCD_PORT)
  File "/usr/local/lib/python2.7/dist-packages/calico-0.14-py2.7.egg/calico/felix/fetcd.py", line 451, in load_config
    global_cfg = client.read("/calico/config/")
  File "/usr/local/lib/python2.7/dist-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 344, in read
    self.key_endpoint + key, self._MGET, params=params, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 582, in api_execute
    return self._handle_server_response(response)
  File "/usr/local/lib/python2.7/dist-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 598, in _handle_server_response
    etcd.EtcdError.handle(**r)
  File "/usr/local/lib/python2.7/dist-packages/python_etcd-0.3.2-py2.7.egg/etcd/__init__.py", line 142, in handle
    raise exc(msg)
KeyError: 'Key not found : /calico'

```

**Comment by Lukasa** [comment]
I've assigned you, @fasaxc, because you're actually going to be working over the next few days, but if you don't think you'll get to this feel free to reassign to someone who will! =)

**Comment by fasaxc** [comment]
Yep, this is in my plan for today.

What's our restart policy for felix at the OS level?  I think it'd be best if the OS didn't give up trying to restart felix.

**Comment by Lukasa** [comment]
Most init services will eventually give up if the process crashes repeatedly shortly after startup. No point wasting CPU on a process that can't start.

**Comment by fasaxc** [comment]
Felix is now resilient to missing data in etcd and there's another issue #348 that covers possible problems with the upstart config.
