### ISSUE TITLE
Calico Felix failing to start due to missing etcd config

### ISSUE THREAD

**Issue by robbrockbank** [Metaswitch/calico#351]
Just installed an OpenStack cluster using chef (based on the new etcd code).

Hitting the following exception in upstart logs:
```
2015-04-13 17:11:31,831 [INFO][3] calico.felix.fetcd 110: (Re)connecting to etcd...
2015-04-13 17:11:31,832 [INFO][3] calico.felix.fetcd 87: Waiting for etcd to be ready and for config to be present.
2015-04-13 17:11:31,832 [INFO][3] urllib3.connectionpool 258: Starting new HTTP connection (1): localhost
2015-04-13 17:11:31,833 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 10
2015-04-13 17:11:31,834 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/config/Ready HTTP/1.1" 200 109
2015-04-13 17:11:31,835 [INFO][3] calico.felix.fetcd 102: etcd is ready.
2015-04-13 17:11:31,835 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 60
2015-04-13 17:11:31,874 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/config/ HTTP/1.1" 200 284
2015-04-13 17:11:31,875 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 60
2015-04-13 17:11:31,877 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/host/calicobobcat-ci02/config/ HTTP/1.1" 404 104
2015-04-13 17:11:31,878 [ERROR][3] calico.felix.fetcd 72: Failed to read config.  Will retry.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 70, in load_config
    config_dict = self._load_config_dict()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 294, in _load_config_dict
    self.config.HOSTNAME)
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 344, in read
    self.key_endpoint + key, self._MGET, params=params, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 582, in api_execute
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 598, in _handle_server_response
    etcd.EtcdError.handle(**r)
  File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 142, in handle
    raise exc(msg)
KeyError: 'Key not found : /calico/host/calicobobcat-ci02/config'
2015-04-13 17:11:36,882 [INFO][3] calico.felix.fetcd 110: (Re)connecting to etcd...
2015-04-13 17:11:36,883 [INFO][3] calico.felix.fetcd 87: Waiting for etcd to be ready and for config to be present.
2015-04-13 17:11:36,883 [INFO][3] urllib3.connectionpool 258: Starting new HTTP connection (1): localhost
2015-04-13 17:11:36,885 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 10
2015-04-13 17:11:36,886 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/config/Ready HTTP/1.1" 200 109
2015-04-13 17:11:36,886 [INFO][3] calico.felix.fetcd 102: etcd is ready.
2015-04-13 17:11:36,887 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 60
2015-04-13 17:11:36,887 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/config/ HTTP/1.1" 200 284
2015-04-13 17:11:36,888 [DEBUG][3] urllib3.connectionpool 375: Setting read timeout to 60
2015-04-13 17:11:36,888 [DEBUG][3] urllib3.connectionpool 415: "GET /v2/keys/calico/host/calicobobcat-ci02/config/ HTTP/1.1" 404 104
2015-04-13 17:11:36,889 [ERROR][3] calico.felix.fetcd 72: Failed to read config.  Will retry.
```

From a quick query of etcd, looks as though the config subtree is missing

calico@calicobobcat-ci01:~$ etcdctl ls calico
/calico/config
/calico/host
/calico/policy
calico@calicobobcat-ci01:~$ etcdctl ls calico/host
/calico/host/calicobobcat-ci02
/calico/host/calicobobcat-ci03
/calico/host/calicobobcat-ci04
calico@calicobobcat-ci01:~$ etcdctl ls calico/host/calicobobcat-ci02
/calico/host/calicobobcat-ci02/workload
calico@calicobobcat-ci01:~$ etcdctl ls calico/host/calicobobcat-ci02/workload
/calico/host/calicobobcat-ci02/workload/openstack
calico@calicobobcat-ci01:~$ etcdctl ls calico/host/calicobobcat-ci02/workload/openstack
/calico/host/calicobobcat-ci02/workload/openstack/endpoint
calico@calicobobcat-ci01:~$ etcdctl ls calico/host/calicobobcat-ci02/workload/openstack/endpoint
calico@calicobobcat-ci01:~$ etcdctl ls calico/host/calicobobcat-ci02/workload/openstack/endpoint
/calico/host/calicobobcat-ci02/workload/openstack/endpoint/85437733-b5e5-4e40-aada-70cdc3157713
calico@calicobobcat-ci01:~$

**Comment by robbrockbank** [comment]
Let me know if there are additional diags that would be useful here.

**Comment by fasaxc** [comment]
Should be fixed on branch smc-fix-missing-config (doesn't include fix to the deb deps).

**Comment by fasaxc** [comment]
Think this is fixed.
