### ISSUE TITLE
Felix fails to program rules for ICMP port

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#414]
Looks like a mismatch between plugin and felix: the plugin is specifying both icmp_type and ports.  Also looks like felix needs to handle multiple ICMP ports and port ranges, which we may not at present (just spotted that multiport doesn't support icmp, d'oh).

```
Apr 18 19:58:33.553531 10.41.0.18 err calico-felix: Failed to convert rules to fragments: [{'ip_version': 4, 'src_tag': u'ed1c1daf-8cb8-44c8-a2cc-6ca518f31301', 'icmp_type': 255, 'protocol': u'icmp', 'dst_ports': [255]}].  Will DROP!
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/calico/felix/frules.py", line 153, in rules_to_chain_rewrite_lines
  File "/usr/lib64/python2.7/site-packages/calico/felix/frules.py", line 209, in rule_to_iptables_fragments
  File "/usr/lib64/python2.7/site-packages/calico/felix/frules.py", line 295, in _rule_to_iptables_fragment
AssertionError: Protocol icmp not supported with dst_ports ({'protocol': u'icmp', 'dst_ports': ['255'], 'src_tag': u'ed1c1daf-8cb8-44c8-a2cc-6ca518f31301', 'ip_version': 4, 'icmp_type': 255, 'src_ports': []})
```

**Comment by fasaxc** [comment]
Looks like there's also a missing field in the data model.  OpenStack lets you match on ICMP code as well but we don't have a field for that.  I'll write up a suggestion in the datamodel design doc.
