### ISSUE TITLE
Unable to delete a security group from an OpenStack guest VM

### ISSUE THREAD

**Issue by robbrockbank** [Metaswitch/calico#465]
I'm performing some fast "toggling" of a security group from on a VM - whereby I'm quickly adding and removing a security group from a VM.  I'm using the NovaClient to do this.

At some point I hit an exception in the NovaClient attempting to remove the security group from the VM.  This error in the client coincides with exceptions raised in the neutron server logs in the calico plugin code.

Details of the exception raised in my test harness, and stack traces from the control nodes are shown below.

I can provide full trace of this - but it's quite large.  Just let me know.

2015-04-27 04:48:06,420 [ERROR][15539] calicotest.common.testutils 30: Test calicotest.openstack.test_security_groups.TestBasicSecurityGroups.test_add_remove_group terminated with exception
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test-class/calicotest/common/testutils.py", line 22, in call_test_hooks
    test_method(self)
  File "/var/lib/jenkins/workspace/test-class/calicotest/openstack/test_security_groups.py", line 190, in test_add_remove_group
    self._add_remove_group(False)
  File "/var/lib/jenkins/workspace/test-class/calicotest/openstack/test_security_groups.py", line 272, in _add_remove_group
    remove_security_group()
  File "/var/lib/jenkins/workspace/test-class/calicotest/openstack/test_security_groups.py", line 224, in remove_security_group
    test_vm.remove_security_group(self.security_group.name)
  File "/var/lib/jenkins/workspace/test-class/calicotest/openstack/vm.py", line 194, in remove_security_group
    self.vm.remove_security_group(groupname)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/v1_1/servers.py", line 368, in remove_security_group
    self.manager.remove_security_group(self, security_group)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/v1_1/servers.py", line 1160, in remove_security_group
    self._action('removeSecurityGroup', server, {'name': security_group})
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/v1_1/servers.py", line 1240, in _action
    return self.api.client.post(url, body=body)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/client.py", line 490, in post
    return self._cs_request(url, 'POST', **kwargs)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/client.py", line 465, in _cs_request
    resp, body = self._time_request(url, method, **kwargs)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/client.py", line 439, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/var/lib/jenkins/workspace/test-class/env/local/lib/python2.7/site-packages/novaclient/client.py", line 433, in request
    raise exceptions.from_response(resp, body, url, method)
ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e6add1a7-f9ba-473b-a5fc-93d9b641972f)
2015-04-27 04:48:06,442 [INFO][15539] calicotest.openstack.basetest 157: Gather diagnostics from failure
ERROR

2015-04-27 04:56:01,003 [ERROR][15539] calicotest.openstack.basetest 122: ***** Start of errors in logs from /var/log/neutron/server.log on calicobobcat-ci01.gulfstream.datcon.co.uk *****

=== LOG 2015-04-26 20:48:06 ERROR [pid 1093] ===
neutron.plugins.ml2.managers [req-fad2d6c1-d12f-4888-a837-c706455ab141 None] Mechanism driver 'calico' failed in update_port_postcommit
neutron.plugins.ml2.managers Traceback (most recent call last):
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 168, in _call_on_drivers
neutron.plugins.ml2.managers     getattr(driver.obj, method_name)(context)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 188, in update_port_postcommit
neutron.plugins.ml2.managers     self.transport.endpoint_updated(port)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 298, in endpoint_updated
neutron.plugins.ml2.managers     self.endpoint_created(port)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 294, in endpoint_created
neutron.plugins.ml2.managers     self.write_profile_to_etcd(profile_id)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 263, in write_profile_to_etcd
neutron.plugins.ml2.managers     json.dumps(self.profile_rules(profile_id)))
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 271, in profile_rules
neutron.plugins.ml2.managers     for rule in self.sgs[sgid]['security_group_rules']:
neutron.plugins.ml2.managers KeyError: u'34420f35-8636-4ef1-b6b0-083038f3c1ee'
neutron.plugins.ml2.managers

=== LOG 2015-04-26 20:48:06 ERROR [pid 1093] ===
neutron.api.v2.resource [req-fad2d6c1-d12f-4888-a837-c706455ab141 None] update failed
neutron.api.v2.resource Traceback (most recent call last):
neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 87, in resource
neutron.api.v2.resource     result = method(request=request, **args)
neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 541, in update
neutron.api.v2.resource     obj = obj_updater(request.context, id, **kwargs)
neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/plugin.py", line 698, in update_port
neutron.api.v2.resource     self.mechanism_manager.update_port_postcommit(mech_context)
neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 407, in update_port_postcommit
neutron.api.v2.resource     self._call_on_drivers("update_port_postcommit", context)
neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 179, in _call_on_drivers
neutron.api.v2.resource     method=method_name
neutron.api.v2.resource MechanismDriverError: update_port_postcommit failed.
neutron.api.v2.resource

2015-04-27 04:56:01,004 [ERROR][15539] calicotest.openstack.basetest 124: ****** End of errors in logs from /var/log/neutron/server.log on calicobobcat-ci01.gulfstream.datcon.co.uk ******

**Comment by Lukasa** [comment]
In the absence of other priority information, assigning this to 0.19 and @neiljerram for initial triage.

**Comment by ed-harrison** [comment]
Hoping this is similar to #489, so setting the same milestone.

**Comment by neiljerram** [comment]
Believed fixed by #508
