### ISSUE TITLE
EtcdException: Unable to decode server response

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#470]
In the Neutron server log, on the controller node in an OpenStack/Calico cluster:

    2015-04-27 21:38:06.988 25929 ERROR calico.openstack.mech_calico [-] Exception in periodic resync thread
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico Traceback (most recent call last):
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 88, in periodic_resync_thread
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     self.provide_felix_config()
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 333, in provide_felix_config
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     prefix = self.client.read(iface_pfx_key).value
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 349, in read
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     timeout=timeout, check_cluster_uuid=check_cluster_uuid)
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 610, in api_execute
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     return self._handle_server_response(response)
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 626, in _handle_server_response
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     etcd.EtcdError.handle(**r)
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 193, in handle
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico     raise exc(msg, payload)
    2015-04-27 21:38:06.988 25929 TRACE calico.openstack.mech_calico EtcdException: Unable to decode server response

**Comment by neiljerram** [comment]
This is an exception that can be caused by transient connection errors to the etcd cluster.  The system (specifically Neutron server and the Calico mechanism driver) handles and recovers from it and runs correctly afterwards without requiring a restart.  Therefore we don't plan any change to 'fix' this.

**Comment by lwr20** [comment]
If you see this continuously, investigate the network conditions between the host you see this on and the etcd cluster.
