### ISSUE TITLE
Felix crash: NameError: global name 'StringTypes' is not defined

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#480]
Spotted by the CI rig.

Full stacktrace:
2015-04-29 11:09:31,195 [ERROR][24174/3] calico.felix.actor 234: Exception processing 8561fb60eb46 (watch_etcd)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 232, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 159, in watch_etcd
    endpoint_id, endpoint = parse_if_endpoint(self.config, child)
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 381, in parse_if_endpoint
    common.validate_endpoint(config, endpoint)
  File "/usr/lib/python2.7/dist-packages/calico/common.py", line 266, in validate_endpoint
    elif not isinstance(endpoint[field], StringTypes):
NameError: global name 'StringTypes' is not defined
2015-04-29 11:09:31,196 [ERROR][24174/2] calico.felix.felix 151: Greenlet failed: <TrackedAsyncResult value=None exception=NameError("global name 'StringTypes' is not defined",)  _links[0]>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 149, in _main_greenlet
    stopped_greenlet.get()
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 473, in get
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
    raise self._exception
NameError: global name 'StringTypes' is not defined
2015-04-29 11:09:31,197 [ERROR][24174/2] calico.felix.felix 157: Exception killing main greenlet
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 149, in _main_greenlet
    stopped_greenlet.get()
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 473, in get
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
    raise self._exception
NameError: global name 'StringTypes' is not defined

**Comment by matthewdupre** [comment]
common.py doesn't import this.
