### ISSUE TITLE
MySQL errors from mech calico

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#482]
When I start neutron-server, I see the following logs almost immediately from mech_calico:

```
2015-04-29 14:29:01.335 28537 ERROR calico.openstack.mech_calico [req-65265ef2-1155-4420-8a0e-877404485c23 None] Exception in periodic resync thread
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico Traceback (most recent call last):
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 91, in periodic_resync_thread
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     self.resync_endpoints()
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 106, in resync_endpoints
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     for port in self.driver.get_endpoints():
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 213, in get_endpoints
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     ports = [port for port in self.db.get_ports(db_context)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/neutron/db/db_base_plugin_v2.py", line 1483, in get_ports
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     items = [self._make_port_dict(c, fields) for c in query]
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     return self._execute_and_instances(context)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     result = conn.execute(querycontext.statement, self._params)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     return meth(self, multiparams, params)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     return connection._execute_clauseelement(self, multiparams, params)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     compiled_sql, distilled_params
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     context)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1156, in _handle_dbapi_exception
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     util.raise_from_cause(newraise, exc_info)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     reraise(type(exception), exception, tb=exc_tb)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     context)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     cursor.execute(statement, parameters)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     self.errorhandler(self, exc, value)
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico     raise errorclass, errorvalue
2015-04-29 14:29:01.335 28537 TRACE calico.openstack.mech_calico DBConnectionError: (OperationalError) (2006, 'MySQL server has gone away') 'SELECT ports.tenant_id AS ports_tenant_id, ports.id AS ports_id, ports.name AS ports_name, ports.network_id AS ports_network_id, ports.      mac_address AS ports_mac_address, ports.admin_state_up AS ports_admin_state_up, ports.status AS ports_status, ports.device_id AS ports_device_id, ports.device_owner AS ports_device_owner, ipallocations_1.port_id AS ipallocations_1_port_id, ipallocations_1.ip_address AS             ipallocations_1_ip_address, ipallocations_1.subnet_id AS ipallocations_1_subnet_id, ipallocations_1.network_id AS ipallocations_1_network_id, ml2_port_bindings_1.port_id AS ml2_port_bindings_1_port_id, ml2_port_bindings_1.host AS ml2_port_bindings_1_host, ml2_port_bindings_1.      vnic_type AS ml2_port_bindings_1_vnic_type, ml2_port_bindings_1.profile AS ml2_port_bindings_1_profile, ml2_port_bindings_1.vif_type AS ml2_port_bindings_1_vif_type, ml2_port_bindings_1.vif_details AS ml2_port_bindings_1_vif_details, ml2_port_bindings_1.driver AS                   ml2_port_bindings_1_driver, ml2_port_bindings_1.segment AS ml2_port_bindings_1_segment, allowedaddresspairs_1.port_id AS allowedaddresspairs_1_port_id, allowedaddresspairs_1.mac_address AS allowedaddresspairs_1_mac_address, allowedaddresspairs_1.ip_address AS                       allowedaddresspairs_1_ip_address, ml2_dvr_port_bindings_1.port_id AS ml2_dvr_port_bindings_1_port_id, ml2_dvr_port_bindings_1.host AS ml2_dvr_port_bindings_1_host, ml2_dvr_port_bindings_1.router_id AS ml2_dvr_port_bindings_1_router_id, ml2_dvr_port_bindings_1.vif_type AS           ml2_dvr_port_bindings_1_vif_type, ml2_dvr_port_bindings_1.vif_details AS ml2_dvr_port_bindings_1_vif_details, ml2_dvr_port_bindings_1.vnic_type AS ml2_dvr_port_bindings_1_vnic_type, ml2_dvr_port_bindings_1.profile AS ml2_dvr_port_bindings_1_profile, ml2_dvr_port_bindings_1.        cap_port_filter AS ml2_dvr_port_bindings_1_cap_port_filter, ml2_dvr_port_bindings_1.driver AS ml2_dvr_port_bindings_1_driver, ml2_dvr_port_bindings_1.segment AS ml2_dvr_port_bindings_1_segment, ml2_dvr_port_bindings_1.status AS ml2_dvr_port_bindings_1_status,                       securitygroupportbindings_1.port_id AS securitygroupportbindings_1_port_id, securitygroupportbindings_1.security_group_id AS securitygroupportbindings_1_security_group_id, extradhcpopts_1.id AS extradhcpopts_1_id, extradhcpopts_1.port_id AS extradhcpopts_1_port_id, extradhcpopts_1.opt_name AS extradhcpopts_1_opt_name, extradhcpopts_1.opt_value AS extradhcpopts_1_opt_value \nFROM ports LEFT OUTER JOIN ml2_port_bindings ON ports.id = ml2_port_bindings.port_id LEFT OUTER JOIN ipallocations AS ipallocations_1 ON ports.id = ipallocations_1.port_id LEFT OUTER     JOIN ml2_port_bindings AS ml2_port_bindings_1 ON ports.id = ml2_port_bindings_1.port_id LEFT OUTER JOIN allowedaddresspairs AS allowedaddresspairs_1 ON ports.id = allowedaddresspairs_1.port_id LEFT OUTER JOIN ml2_dvr_port_bindings AS ml2_dvr_port_bindings_1 ON ports.id =           ml2_dvr_port_bindings_1.port_id LEFT OUTER JOIN securitygroupportbindings AS securitygroupportbindings_1 ON ports.id = securitygroupportbindings_1.port_id LEFT OUTER JOIN extradhcpopts AS extradhcpopts_1 ON ports.id = extradhcpopts_1.port_id' ()
```

If I then attempt to create a VM, everything dies in a fire:

```
2015-04-29 14:35:45.050 28547 INFO oslo.messaging._drivers.impl_rabbit [req-5db7e2f2-ea0f-4f03-9fa7-2fbd4c3bb812 ] Connecting to AMQP server on ip-10-32-54-94.eu-west-1.compute.internal:5672
2015-04-29 14:35:45.061 28547 INFO oslo.messaging._drivers.impl_rabbit [req-5db7e2f2-ea0f-4f03-9fa7-2fbd4c3bb812 ] Connected to AMQP server on ip-10-32-54-94.eu-west-1.compute.internal:5672
2015-04-29 14:35:45.241 28547 ERROR neutron.plugins.ml2.managers [req-5db7e2f2-ea0f-4f03-9fa7-2fbd4c3bb812 None] Mechanism driver 'calico' failed in create_port_postcommit
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers Traceback (most recent call last):
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 291, in _call_on_drivers
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers     getattr(driver.obj, method_name)(context)
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 139, in create_port_postcommit
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers     self.transport.endpoint_created(port)
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 294, in endpoint_created
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers     self.write_profile_to_etcd(profile_id)
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 263, in write_profile_to_etcd
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers     json.dumps(self.profile_rules(profile_id)))
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 271, in profile_rules
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers     for rule in self.sgs[sgid]['security_group_rules']:
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers KeyError: u'4217729f-bfb4-4c9c-88be-56c587914177'
2015-04-29 14:35:45.241 28547 TRACE neutron.plugins.ml2.managers
2015-04-29 14:35:45.244 28547 ERROR neutron.plugins.ml2.plugin [req-5db7e2f2-ea0f-4f03-9fa7-2fbd4c3bb812 None] mechanism_manager.create_port_postcommit failed, deleting port 'd1462150-da21-4dbc-9c0f-3db35df6d00e'
2015-04-29 14:35:45.451 28547 ERROR neutron.api.v2.resource [req-5db7e2f2-ea0f-4f03-9fa7-2fbd4c3bb812 None] create failed
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 87, in resource
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 448, in create
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, **kwargs)
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/plugin.py", line 810, in create_port
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     self.delete_port(context, result['id'])
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/excutils.py", line 82, in __exit__
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/plugin.py", line 805, in create_port
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     self.mechanism_manager.create_port_postcommit(mech_context)
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 500, in create_port_postcommit
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     self._call_on_drivers("create_port_postcommit", context)
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 302, in _call_on_drivers
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource     method=method_name
2015-04-29 14:35:45.451 28547 TRACE neutron.api.v2.resource MechanismDriverError: create_port_postcommit failed.
```

**Comment by fasaxc** [comment]
@Lukasa  Why is this against 0.19?  "Plugin dies" seems serious!

**Comment by Lukasa** [comment]
The main reason is that I don't know the actual severity of this bug, but I doubt the fix is totally trivial. It's also not clear that it's our fault, as per the note about MySQL above. However, if it is our fault, diagnosing it is probably going to be a bit tricky.

**Comment by ed-harrison** [comment]
I think this does look serious (not least as it also seems related to #489 and #465.  Consequently, I think we should target 0.18 (i.e. prioritise looking into this ASAP); if it turns out this is tricky, then we can move the milestone, but I'd rather start looking at it now, not leave it until next week.

**Comment by neiljerram** [comment]
The KeyError aspect of this is believed fixed by #508.  The MySQL DB part is still unaddressed, but has not been seen again and is believed not urgent for the 0.18 release.  Hence deferring this to 0.19.

**Comment by lxpollitt** [comment]
@neiljerram - I'm confused as to what the status of this issue is meant to be.  It seems it was both deferred to 0.19 and closed at the same time, but there is no comment indicating that the headline issue has been resolved?

**Comment by lxpollitt** [comment]
So I reopened.  If that's wrong then feel free to close again with a comment to make it a bit clearer as to why...

**Comment by neiljerram** [comment]
Thanks @lxpollitt. I didn't intend to close this - sorry!

**Comment by fasaxc** [comment]
So, I think @Lukasa put in a work around that blocks VM creation until we've successfully connected to MySQL and got the SGs.  If we can connect to MySQL at all, that should do it, if not, what else can we do?

**Comment by Lukasa** [comment]
@neiljerram and I actually believe these mysql errors were coming because of the forking logic in Neutron. I suspect the forking fix resolves this problem.
