### ISSUE TITLE
FV failure

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#486]
Felix.log says:

2015-04-29 16:57:19,968 [ERROR][20551/3] calico.felix.actor 234: Exception processing 36889712139b (watch_etcd)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 232, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 158, in watch_etcd
    endpoint_id, endpoint = parse_if_endpoint(self.config, child)
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 380, in parse_if_endpoint
    common.validate_endpoint(config, endpoint)
  File "/usr/lib/python2.7/dist-packages/calico/common.py", line 290, in validate_endpoint
    if gw_str is not None and not common.validate_ip_addr(gw_str,
NameError: global name 'common' is not defined
2015-04-29 16:57:19,969 [ERROR][20551/2] calico.felix.felix 151: Greenlet failed: <TrackedAsyncResult value=None exception=NameError("global name 'common' is no
t defined",)  _links[0]>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 149, in _main_greenlet
    stopped_greenlet.get()
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 473, in get
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
    raise self._exception
NameError: global name 'common' is not defined
2015-04-29 16:57:19,970 [ERROR][20551/2] calico.felix.felix 157: Exception killing main greenlet
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 149, in _main_greenlet
    stopped_greenlet.get()
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 473, in get
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
    raise self._exception
NameError: global name 'common' is not defined

**Comment by Lukasa** [comment]
See #487.
