### ISSUE TITLE
Memory allocation exception gets swallowed.

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#520]
I was running mismatched versions of plugin and felix (accidentally). This caused a memory leak. Eventually memory allocation exceptions were raised, but handled. These continued. Probably should do something better here, like restart felix.

2015-05-07 21:34:55,701 [ERROR][3523/7399] calico.felix.actor 227: Exception processing 3f1bd9f99fef (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/actor.py", line 225, in _step
    result = msg.method()
  File "/usr/lib/python2.7/site-packages/calico/felix/endpoint.py", line 238, in on_endpoint_update
    self._deconfigure_interface()
  File "/usr/lib/python2.7/site-packages/calico/felix/endpoint.py", line 376, in _deconfigure_interface
    devices.set_routes(self.ip_type, set(), self._iface_name, None)
  File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 182, in set_routes
    current_ips = list_interface_ips(ip_type, interface)
  File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 59, in list_interface_ips
    ["ip", "route", "list", "dev", interface]).stdout
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 100, in check_call
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/site-packages/gevent/subprocess.py", line 646, in _execute_child
    self.pid = fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by fasaxc** [comment]
That's odd, the exception should get put into the result object, which should either get handled or cause Felix to get killed later on if it doesn't get handled.

**Comment by Lukasa** [comment]
It's coming from gevent on an OOM condition: I think at this stage you can assume that nothing sensible happens.

**Comment by fasaxc** [comment]
Annoyingly, it's not even a BaseException because it's wrapping an errno.  Either way, Felix should die if such an exception is not handled; I'll have to dig into why that's not happening.

**Comment by fasaxc** [comment]
I believe swallowing the error was caused by the same issue that was leaking memory in the first place: #523

**Comment by neiljerram** [comment]
Looks like this issue should be closed now.  @DaveLangridge or @Lukasa , please can you confirm?

**Comment by DaveLangridge** [comment]
Looks like it should be fixed by #523. Not tested yet.
