### ISSUE TITLE
Felix runs out of file descriptors at around 160 instances on one host

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico#534]
I'm running with the default ulimit of 1024, and after creating 160 VMs it stopped setting up new VMs and cyclically restarted.  We should consider reducing the number of file handles used and (if we can't remove the relation to number of instances) document that the limit may need increasing.
```
2015-05-13 17:47:25,134 [ERROR][12169/352] calico.felix.actor 227: Exception processing 597b3eb38cf7 (on_endpoint_update)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 225, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/endpoint.py", line 235, in on_endpoint_update
    self._configure_interface()
  File "/usr/lib/python2.7/dist-packages/calico/felix/endpoint.py", line 360, in _configure_interface
    self.endpoint["mac"])
  File "/usr/lib/python2.7/dist-packages/calico/felix/devices.py", line 182, in set_routes
  File "/usr/lib/python2.7/dist-packages/calico/felix/devices.py", line 62, in list_interface_ips
  File "/usr/lib/python2.7/dist-packages/calico/felix/futils.py", line 100, in check_call
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 238, in __init__
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 638, in _execute_child
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 594, in pipe_cloexec
OSError: [Errno 24] Too many open files
2015-05-13 17:47:25,140 [CRITICAL][12169/352] calico.felix.actor 511: TrackedAsyncResult ('endpoint.py:82:_on_object_started', 'EndpointManager(IPv6) (processing 27dd27bbd479)', u'LocalEndpoint(e3257adf-2ba3-4011-a339-2ceb2d0886c4(IPv6))', 'on_endpoint_update') was leaked with exception OSError(24, 'Too many open files').  Dying.
```

**Comment by fasaxc** [comment]
That's odd.  I'm not sure what we'd be using a proportional number of FDs for.

**Comment by fasaxc** [comment]
Some ideas:
* we're probably using a few hundred for normal things
* could be gevent using FDs for something underneath us
* could simply be that we kick off 160 endpoints and each tries to configure its tap at the same time using a shell-out; each shell-out will take 3 FDs for stdin/out/err.

The latter could be mitigated by adding a Semaphore in futils to limit parallelism. Or, we could simply increase the ulimit.

**Comment by matthewdupre** [comment]
I can further add that increasing the limit (put a `limit nofile 10000 10000` stanza into /etc/init/calico-felix.conf) does increase the number of VMs Felix can handle.

**Comment by plwhite** [comment]
1024 is an incredibly low number for the FD limit. Most servers are set to either 32K or 64K - I think we should probably just set it to something sensible.

**Comment by alexwlchan** [comment]
Pinging @matthewdupre: now you've merged my PR, can this issue be closed?

**Comment by matthewdupre** [comment]
Yes.
