### ISSUE TITLE
Felix exception during ipsets cleanup

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#541]
During churn test on neutron-ha branch

2015-05-14 14:46:01,457 [ERROR][21795/6] calico.felix.splitter 110: ipsets cleanup failed, will retry on resync.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/splitter.py", line 108, in trigger_cleanup
    ipset_mgr.cleanup(async=False)
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 450, in queue_fn
    return result.get()
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 543, in get
    timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 235, in get
    raise self._exception
AttributeError: 'set' object has no attribute 'owned_ipset_names'

**Comment by fasaxc** [comment]
@DaveLangridge Do you have the whole log for this?  It's probably bretty easy to track down from the owned_ipset_names clue but this is a re-raised error so the stack trace isn't so useful.  there should be another stack trace not far above with same message but with the correct stack.

**Comment by DaveLangridge** [comment]
Is this what you want?

2015-05-14 14:46:01,171 [INFO][21795/878] calico.felix.endpoint 207: Endpoint<IPv6,id=EndpointId<calico-vm15/openstack/4725d075-e899-4232-83b1-636f4a20908f/c110ea3f-3e84-4820-a81a-584402d029ce>,iface=tapc110ea3f-3e> updated: {'ipv4_gateway': u'10.28.0.1', 'name': u'tapc110ea3f-3e', 'state': u'active', 'ipv6_nets': [u'2001:db8:c41:2::1f1c/128'], 'mac': u'fa:16:3e:b0:f2:30', 'ipv4_nets': [u'10.28.31.88/32'], 'ipv6_gateway': u'2001:db8:c41:2::1', 'profile_ids': [u'08c1346b-09d4-468e-a077-0812a7bb8eac']}
2015-05-14 14:46:01,452 [ERROR][21795/10] calico.felix.actor 227: Exception processing 0ef0a097cdb3 (cleanup)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 225, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/ipsets.py", line 154, in cleanup
    whitelist.update(ipset.owned_ipset_names())
AttributeError: 'set' object has no attribute 'owned_ipset_names'

**Comment by plwhite** [comment]
That would do it, thanks.
