### ISSUE TITLE
Elector greenlet kill() call failed, eventlet version difference?

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#578]
The version of eventlet that I have installed locally allows greenlet.kill(Exception()), but the one on the FV server seems to need kill(Exception(), None, None).

**Comment by fasaxc** [comment]
Oh, maybe it's a different code path that I'm hitting.  I'll investigate.  This is the traceback:
```
neutron.plugins.ml2.managers [req-852f9f39-3173-4697-8d17-dcd94ca9362f None] Mechanism driver 'calico' failed in create_port_postcommit
neutron.plugins.ml2.managers Traceback (most recent call last):
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 168, in _call_on_drivers
neutron.plugins.ml2.managers     getattr(driver.obj, method_name)(context)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 106, in wrapper
neutron.plugins.ml2.managers     return f(self, *args, **kwargs)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 83, in wrapper
neutron.plugins.ml2.managers     return f(self, *args, **kwargs)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 284, in create_port_postcommit
neutron.plugins.ml2.managers     self.transport.endpoint_created(port)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 89, in wrapped
neutron.plugins.ml2.managers     self._on_etcd_request_failed()
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 117, in _on_etcd_request_failed
neutron.plugins.ml2.managers     self._initialise()
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 133, in _initialise
neutron.plugins.ml2.managers     self.elector.stop()
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/election.py", line 261, in stop
neutron.plugins.ml2.managers     eventlet.with_timeout(10, self._greenlet.wait)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/eventlet/timeout.py", line 142, in with_timeout
neutron.plugins.ml2.managers     return function(*args, **kwds)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 168, in wait
neutron.plugins.ml2.managers     return self._exit_event.wait()
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/eventlet/event.py", line 120, in wait
neutron.plugins.ml2.managers     current.throw(*self._exc)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 194, in main
neutron.plugins.ml2.managers     result = function(*args, **kwargs)
neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 256, in just_raise
neutron.plugins.ml2.managers     raise throw_args[0], throw_args[1], throw_args[2]
neutron.plugins.ml2.managers IndexError: tuple index out of range
neutron.plugins.ml2.managers
```
