### ISSUE TITLE
Felix exception  doing resynch

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#626]
Hits the exception below periodically. I hav two nodes calico-rh01 is combined control and compute, calico-rh02. rh02 does not have this log, rh01 does.

2015-06-05 10:41:09,070 [ERROR][1098/3] calico.felix.fetcd 321: Unknown etcd error 'Unable to decode server response: timed out'; doing resync.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/fetcd.py", line 282, in _wait_for_etcd_event
    check_cluster_uuid=True)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.3.3_calico_2-py2.7.egg/etcd/client.py", line 357, in read
    return self._result_from_response(response)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.3.3_calico_2-py2.7.egg/etcd/client.py", line 541, in _result_from_response
    'Unable to decode server response: %s' % e)
EtcdException: Unable to decode server response: timed out

Followed by:
2015-06-05 10:41:09,071 [INFO][1098/3] calico.felix.fetcd 173: (Re)connecting to etcd. Old etcd cluster ID was e0c067710be719f2.
2015-06-05 10:41:09,072 [INFO][1098/3] calico.felix.fetcd 205: Polling aborted, doing resync.
2015-06-05 10:41:09,072 [INFO][1098/3] calico.felix.fetcd 190: Reconnecting and loading snapshot from etcd...
2015-06-05 10:41:09,072 [INFO][1098/3] calico.felix.fetcd 175: (Re)connecting to etcd. No previous cluster ID.
2015-06-05 10:41:09,072 [INFO][1098/3] calico.felix.fetcd 137: Waiting for etcd to be ready...
2015-06-05 10:41:09,072 [INFO][1098/3] urllib3.connectionpool 257: Starting new HTTP connection (1): localhost
2015-06-05 10:41:09,078 [INFO][1098/3] calico.felix.fetcd 155: etcd is ready.
2015-06-05 10:41:09,081 [INFO][1098/3] calico.felix.fetcd 215: Loaded snapshot from etcd cluster e0c067710be719f2, parsing it...
2015-06-05 10:41:09,083 [INFO][1098/3] calico.felix.fetcd 252: Snapshot parsed, passing to update splitter
2015-06-05 10:41:09,084 [INFO][1098/7] calico.felix.splitter 61: Applying snapshot. STAGE 1a: rules.
2015-06-05 10:41:09,084 [INFO][1098/7] calico.felix.splitter 64: Applying snapshot. STAGE 1b: tags.
2015-06-05 10:41:09,084 [INFO][1098/7] calico.felix.splitter 71: Applying snapshot. STAGE 2: endpoints->endpoint mgr.
2015-06-05 10:41:09,085 [INFO][1098/7] calico.felix.splitter 77: Applying snapshot. DONE. 5 rules, 5 tags, 4 endpoints
2015-06-05 10:41:09,085 [INFO][1098/7] calico.felix.splitter 85: No cleanup scheduled, scheduling one.
2015-06-05 10:41:09,085 [INFO][1098/8] calico.felix.profilerules 63: Rules manager applying snapshot; 5 rules
2015-06-05 10:41:09,085 [INFO][1098/8] calico.felix.profilerules 75: Rules for profile 6348aba3-e010-4a3a-b5fb-53930e29b2b4 updated.
2015-06-05 10:41:09,085 [INFO][1098/8] calico.felix.profilerules 75: Rules for profile 109c0510-1a5c-4b4a-90c8-b827acc250eb updated.
2015-06-05 10:41:09,085 [INFO][1098/8] calico.felix.profilerules 75: Rules for profile 6945f875-a515-4e2c-85c4-9b915a803976 updated.

**Comment by fasaxc** [comment]
Triggering the resync looks like another instance of https://github.com/Metaswitch/python-etcd/issues/6.  That timeout should be passed up to our code but it's getting caught and wrapped so our code resorts to a full resync.

OTOH, should we be hitting a timeout here?  Was there anything going on that might have caused the timeout from etcd?

**Comment by DaveLangridge** [comment]
I don't think there was a reason for the timeout. This node was controll + compute, so plugin was writing, and felix reading. The other (compute only) node didn't see any issues.

**Comment by fasaxc** [comment]
@DaveLangridge does that mean that you were directly connected to the etcd master, rather than a proxy?

**Comment by fasaxc** [comment]
No etcd restarts or anything?  I can repro that by hitting etcd with a SIGKILL, but only when I'm directly-connected.

**Comment by DaveLangridge** [comment]
Yes. Plugin and felix both on calico-rh01 directly connected to ectd master.

**Comment by fasaxc** [comment]
@DaveLangridge what's the impact of this now we've fixed the python-etcd bug?  I'd expect a log saying there was a timeout but it shouldn't resync.

**Comment by DaveLangridge** [comment]
Its now just logging the following every 90s:

2015-03-03 11:13:42,968 [INFO][30133/3] calico.felix.fetcd 199: (Re)connecting to etcd. Old etcd cluster ID was afacd66dd456fea3.
2015-03-03 11:13:42,968 [INFO][30133/3] urllib3.connectionpool 257: Starting new HTTP connection (1): localhost

No exception, so closing.
