### ISSUE TITLE
Latest version of Glance and Calico don't play nice together

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#646]
Following an attempt to upgrade my redhat system using "yum update -y", my openstack rig stopped working.  Specifically Glance refused to do very much, complaining:

2015-06-10 11:51:42.035 2001 ERROR nova.api.openstack.compute.contrib.admin_actions [req-4a4a9f60-7f08-4417-a74e-edca5e7e1325 None] Error in migrate No module named cryptography.hazmat.bindings.openssl.binding
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/dispatcher.py", line 134, in _dispatch_and_reply
    incoming.message))
  File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/dispatcher.py", line 177, in _dispatch
    return self._do_dispatch(endpoint, method, ctxt, args)
  File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/dispatcher.py", line 123, in _do_dispatch
    result = getattr(endpoint, method)(ctxt, **new_args)
  File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/server.py", line 139, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 490, in migrate_server
    reservations)
  File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 498, in _cold_migrate
    context, self.image_api, image_ref, instance)
  File "/usr/lib/python2.7/site-packages/nova/compute/utils.py", line 214, in get_image_metadata
    image = image_api.get(context, image_id_or_uri)
  File "/usr/lib/python2.7/site-packages/nova/image/api.py", line 89, in get
    include_locations=include_locations)
  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 311, in show
    _reraise_translated_image_exception(image_id)
  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 309, in show
    image = self._client.call(context, version, 'get', image_id)
  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 230, in call
    version)
  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 217, in _create_onetime_client
    self.use_ssl, version)
  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 160, in _create_glance_client
    return glanceclient.Client(str(version), endpoint, **params)
  File "/usr/lib/python2.7/site-packages/glanceclient/client.py", line 37, in Client
    module = utils.import_versioned_module(version, 'client')
  File "/usr/lib/python2.7/site-packages/glanceclient/common/utils.py", line 231, in import_versioned_module
    return importutils.import_module(module)
  File "/usr/lib/python2.7/site-packages/glanceclient/openstack/common/importutils.py", line 57, in import_module
    __import__(import_str)
  File "/usr/lib/python2.7/site-packages/glanceclient/v1/__init__.py", line 16, in <module>
    from glanceclient.v1.client import Client      # noqa
  File "/usr/lib/python2.7/site-packages/glanceclient/v1/client.py", line 16, in <module>
    from glanceclient.common import http
  File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 39, in <module>
    from glanceclient.common import https
  File "/usr/lib/python2.7/site-packages/glanceclient/common/https.py", line 19, in <module>
    import OpenSSL
  File "build/bdist.linux-x86_64/egg/OpenSSL/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/rand.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/_util.py", line 6, in <module>
ImportError: No module named cryptography.hazmat.bindings.openssl.binding

Calico depends on python-etcd, which depends on PyOpenSSL>=0.14.  We *think* that glance doesn't like this.

**Comment by Lukasa** [comment]
The specific problem is that glance works with the version of PyOpenSSL that Red Hat shipped, which is (sadly) 0.13.1. This means that we have a problem: glance requires PyOpenSSL at a lower level than we do.

We do need to confirm that everything is ok here, because I believe that we probably screwed up the install, but we'll see.

**Comment by matthewdupre** [comment]
I've gone from an up to date OpenStack Juno install on RHEL7, and installed Calico without seeing any issues.  I can import cryptography.hazmat.bindings.openssl.binding without issues, and Glance starts up fine.  VM boots work etc.

**Comment by matthewdupre** [comment]
The only possible remaining issue here is if the update from an older system with Calico already installed fails.  @Lukasa - you looked at this originally: do you think that's worth testing or should we just close this?

**Comment by Lukasa** [comment]
I think it could fail, yeah. The particular problem is that we install pyOpenSSL quietly in the background, and RHEL might blow it up when Glance ends up requiring it. Just conjecture now though.

**Comment by eepyaich** [comment]
OK - so we do need to retest this, then?

**Comment by matthewdupre** [comment]
I think we should try to, although it might be a bit awkward.  We need to install Calico without updating any packages, and then try and update it.  I'm not totally sure this will be representative though - if it's not then there's not a lot we can do.

**Comment by matthewdupre** [comment]
I've also tried it the other way round (install python-etcd on top of a very old Glance, then update): no issues.
