### ISSUE TITLE
If /calico/v1/ipam/v4/pool/ is not JSON, Felix falls over.

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico#657]
This was a change for IP-in-IP support.

After Felix hits the exception, it dies.

Either that change is back compatible, and we should not hit this error, or the data model version number needs to be bumped.

https://transfer.sh/ZvIgE/diags-160615-142633.tar.gz

```
2015-06-16 21:27:12,453 [WARNING][14584/3] calico.felix.fetcd 703: Failed to decode JSON for ipam pool 11: u'192.168.0.0/16'.  Returning None.
2015-06-16 21:27:12,453 [ERROR][14584/3] calico.felix.actor 233: Exception processing e1c3bda65cd2 (watch_etcd)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 231, in _step
    result = msg.method()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 225, in watch_etcd
    self.load_initial_dump()
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 263, in load_initial_dump
    pool_id, pool = parse_if_ipam_v4_pool(child)
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 681, in parse_if_ipam_v4_pool
    pool = parse_ipam_pool(pool_id, etcd_node.value)
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 689, in parse_ipam_pool
    common.validate_ipam_pool(pool_id, pool, 4)
  File "/usr/lib/python2.7/dist-packages/calico/common.py", line 590, in validate_ipam_pool
    for key in pool:
TypeError: 'NoneType' object is not iterable
```

**Comment by plwhite** [comment]
Should probably be with @fasaxc
