### ISSUE TITLE
Felix: Syslog log format lacks tag

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#71]
When starting felix (and possibly the other daemons), anything going to syslog does not have a properly formatted tag.  Due to this, syslog support is pretty much useless.  For example:

Dec 19 19:00:46.010231 10.45.0.5 exiting after uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/calico/felix/felix.py", line 725, in main
    agent.run()
  File "/usr/lib64/python2.7/site-packages/calico/felix/felix.py", line 606, in run
    polled_sockets = dict(lPoller.poll(self.config.EP_RETRY_INT_MS))
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/poll.py", line 101, in poll
  File "_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1678)
  File "checkrc.pxd", line 11, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1879)
KeyboardInterrupt
Dec 19 19:00:49.638127 10.45.0.5 starting 
Dec 19 19:00:49.638517 10.45.0.5 socket to entity 127.0.0.1:9902
Dec 19 19:00:49.639025 10.45.0.5 socket to entity 127.0.0.1:9901
Dec 19 19:00:49.639267 10.45.0.5 socket to entity 127.0.0.1:9905
Dec 19 19:00:49.639514 10.45.0.5 socket to entity 127.0.0.1:9906

This should look more like:
Dec 19 19:00:49.638127 10.45.0.5 calico-felix: starting

**Comment by Lukasa** [comment]
This was resolved by #75 and the fix is now in `master`. Thanks for the report @nbartos!
